version: '3.6'
services:
  ktordb:
    build: ./postgres
    image: ktordb:latest
    volumes:
      - /tmp/ktordb:/var/lib/postgresql/data
  ktorservice:
    build: .
    image: ktorservice:latest
    ports:
      - "4567:4567"
    depends_on:
      - ktordb